# Generated by Django 4.1 on 2022-08-05 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=100)),
                ('group_create_date', models.DateField(auto_now=True)),
                ('group_active', models.BooleanField(default=True)),
            ],
        ),
    ]
