# Generated by Django 4.1 on 2022-08-05 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursedata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_fio', models.CharField(max_length=150)),
                ('student_create_date', models.DateField(auto_now=True)),
                ('student_active', models.BooleanField(default=True)),
                ('student_phone', models.CharField(max_length=60)),
            ],
        ),
    ]
