# Generated by Django 4.1 on 2022-08-05 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coursedata', '0003_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentParent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_parent_active', models.BooleanField(default=True)),
                ('parent_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coursedata.parent')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coursedata.student')),
            ],
        ),
    ]
