# Generated by Django 4.1 on 2022-08-06 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coursedata', '0004_studentparent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentparent',
            old_name='parent_id',
            new_name='parent',
        ),
        migrations.RenameField(
            model_name='studentparent',
            old_name='student_id',
            new_name='student',
        ),
    ]
