# Generated by Django 4.1 on 2022-08-06 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursedata', '0007_alter_parent_parent_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groups',
            name='group_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
