# Generated by Django 4.1 on 2022-08-06 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursedata', '0008_alter_groups_group_name'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='studentparent',
            constraint=models.UniqueConstraint(models.F('student_id'), models.F('parent_id'), name='student_parent_unique'),
        ),
    ]
