# Generated by Django 4.1 on 2022-08-08 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coursedata', '0009_studentparent_student_parent_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_group_active', models.BooleanField(default=True)),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coursedata.groups')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coursedata.student')),
            ],
        ),
        migrations.AddConstraint(
            model_name='studentgroup',
            constraint=models.UniqueConstraint(models.F('student_id'), models.F('group_id'), name='student_group_unique'),
        ),
    ]
