# Generated by Django 4.1 on 2022-08-08 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursedata', '0011_student_student_email_student_student_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_photo',
            field=models.ImageField(upload_to='student_images/'),
        ),
    ]
