# Generated by Django 4.1 on 2022-08-08 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coursedata', '0013_hotel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hotel',
        ),
    ]
