# Generated by Django 4.1 on 2022-08-08 09:48

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coursedata', '0010_studentgroup_studentgroup_student_group_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExamGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_group_date', models.DateField(auto_now=True)),
                ('exam_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.exam')),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coursedata.groups')),
            ],
        ),
        migrations.CreateModel(
            name='ExamStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_student_date', models.DateField(auto_now=True)),
                ('exam_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.exam')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coursedata.student')),
            ],
        ),
        migrations.CreateModel(
            name='ExamStudentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_percent', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('exam_comment', models.CharField(max_length=255)),
                ('exam_student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.examstudent')),
                ('student_group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coursedata.studentgroup')),
            ],
        ),
        migrations.CreateModel(
            name='ExamGroupResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_percent', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('exam_comment', models.CharField(max_length=255)),
                ('exam_group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.examgroup')),
                ('student_group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coursedata.studentgroup')),
            ],
        ),
        migrations.AddConstraint(
            model_name='examstudentresult',
            constraint=models.UniqueConstraint(models.F('exam_student_id'), models.F('student_group_id'), name='exam_student_result_unique'),
        ),
        migrations.AddConstraint(
            model_name='examstudent',
            constraint=models.UniqueConstraint(models.F('exam_id'), models.F('student_id'), models.F('exam_student_date'), name='exam_student_date_unique'),
        ),
        migrations.AddConstraint(
            model_name='examgroupresult',
            constraint=models.UniqueConstraint(models.F('exam_group_id'), models.F('student_group_id'), name='exam_group_result_unique'),
        ),
        migrations.AddConstraint(
            model_name='examgroup',
            constraint=models.UniqueConstraint(models.F('exam_id'), models.F('group_id'), models.F('exam_group_date'), name='exam_group_date_unique'),
        ),
    ]
