# Generated by Django 4.1 on 2022-08-15 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examgroup',
            name='exam_group_date',
            field=models.DateField(),
        ),
    ]
