# Generated by Django 4.1 on 2022-08-15 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_alter_examgroup_exam_group_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examstudent',
            name='exam_student_date',
            field=models.DateField(),
        ),
    ]
